version: '2'
services:
  client:
    restart: always
    build:
      context: ./client
      dockerfile: ./Dockerfile
    command: []
    ports:
      - "3001:80"
    volumes:
      - ./client/app:/app
  client_redis:
    image: "redis:alpine"
    command: --port 6381
  serwer:
    restart: always
    build:
      context: ./serwer
      dockerfile: ./Dockerfile
    command: []
    ports:
      - "3000:80"
    volumes:
      - ./serwer/app:/app
  serwer_redis:
    image: "redis:alpine"
    command: --port 6380
