version: '2'
services:
  webserwer:
    container_name: pamiw
    restart: always
    build:
      context: .
      dockerfile: ./serwer/Dockerfile
    command: []
    ports:
      - "3000:80"
    volumes:
      - ./server:/app
  webclient:
    container_name: rejestracja
    restart: always
    build:
      context: .
      dockerfile: ./client/Dockerfile
    command: []
    ports:
      - "3001:80"
    volumes:
      - ./client:/app
