version: '2'
services:
  web:
    container_name: client
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: []
    ports:
      - "3001:80"
    volumes:
      - ./app:/app
